name: Build

on:
  push:
    branches: [ main ]
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "~1.20"

      - name: Run GoReleaser (release)
        uses: goreleaser/goreleaser-action@v3
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          version: "~1.16"
          args: "release --clean"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser (snapshot)
        uses: goreleaser/goreleaser-action@v3
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          version: "~1.16"
          args: "build --snapshot --clean --single-target"
